[shell]
# Shell related configuration

# The paths to prepend to the PATH environment variable
# user_paths = ["path1", "path2"]

# The hook to run on shell startup
# hook = "echo hello world"

[dependencies]
# List all dependencies

# Dependency must have a version or use latest
# git = "latest"
# postgresql = "12"

[env]
# Environment variables to set, e.g.
# RUST_BACKTRACE = "1"
# RUST_LOG = "debug"

[scripts]
# Custom script that can be run with `brewer run <name>`
# script1 = "cargo build"
# script2 = "cargo build --release"

[services]
# Services to run, e.g.
# [services.postgresql]
# script = "{pkg.postgresql}/bin/postgres -D {var.state_dir/postgres}"
# env.PGHOST = "localhost"

[var]
# Variables that can be reused across the scripts
# Now you can use {var.MYVAR1} in the scripts/env/hook
# MYVAR1 = "value"
