name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cross
      run: cargo install cross
    - name: Build
      run: |
        mkdir artifacts
        for target in aarch64-unknown-linux-musl x86_64-unknown-linux-musl; do
          echo Buildling $target
          cross build --release --target=$target && \
            mv -v target/$target/release/brewer artifacts/brewer.$target
        done
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts
