name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install x86/arm musl targets
      run: |
        rustup target add aarch64-unknown-linux-musl
        rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: |
        mkdir artifacts
        for target in aarch64-unknown-linux-musl x86_64-unknown-linux-musl; do
          echo Building $target
          cargo build --release --target=$target && \
            mv -v target/$target/release/brewer artifacts/brewer.$target
        done
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts

  build_apple:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install rust targets
      run: |
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
    - name: Build
      run: |
        mkdir artifacts
        for target in aarch64-apple-darwin x86_64-apple-darwin; do
          echo Building $target
          cargo build --release --target=$target && \
            mv -v target/$target/release/brewer artifacts/brewer.$target
        done
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: artifacts