name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [aarch64-unknown-linux-musl, x86_64-unknown-linux-musl]
    steps:
    - uses: actions/checkout@v3
    - name: Install cross
      run: cargo install cross
    - name: Build
      run: cross build --release --target=${{ matrix.target }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/brewer

  build_apple:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [aarch64-apple-darwin, x86_64-apple-darwin]
    steps:
    - uses: actions/checkout@v3
    - name: Install rust target
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --release --target=${{ matrix.target }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/brewer